import Testing
import Foundation
@testable import KataGoOnAppleSilicon

/// Cross-validation tests: replay a GTP command script through Swift's
/// `GTPHandler` and diff the concatenated responses byte-for-byte against
/// KataGo's reference output for the same script.
///
/// Reference files are generated by `Scripts/generate_gtp_reference.sh`
/// and stored under `Tests/KataGoOnAppleSiliconIntegrationTests/ReferenceOutputs/`.
/// They are not committed (see `.gitignore`); run the generator once to
/// produce them locally before running these tests.
struct GTPFixtureTests {

    enum FixtureError: Error, CustomStringConvertible {
        case fileNotFound(String)
        var description: String {
            switch self {
            case .fileNotFound(let path): return "Fixture file not found: \(path)"
            }
        }
    }

    private func repoURL(subdir: String, name: String, ext: String) throws -> URL {
        let fm = FileManager.default
        var here = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        for _ in 0..<8 {
            let candidate = here
                .appendingPathComponent(subdir, isDirectory: true)
                .appendingPathComponent("\(name).\(ext)")
            if fm.fileExists(atPath: candidate.path) { return candidate }
            here.deleteLastPathComponent()
        }
        throw FixtureError.fileNotFound("\(subdir)/\(name).\(ext)")
    }

    /// Returns empty string on match, or a human-readable diff on mismatch.
    private func runFixture(_ name: String) throws -> String {
        let fixtureURL = try repoURL(subdir: "Scripts/GTPFixtures", name: name, ext: "gtp")
        let referenceURL = try repoURL(
            subdir: "Tests/KataGoOnAppleSiliconIntegrationTests/ReferenceOutputs",
            name: name,
            ext: "txt"
        )
        let fixtureText = try String(contentsOf: fixtureURL, encoding: .utf8)
        let reference = try String(contentsOf: referenceURL, encoding: .utf8)

        let katago = KataGoInference()
        let handler = GTPHandler(katago: katago)
        var buffer = ""
        for rawLine in fixtureText.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            if line.isEmpty { continue }
            buffer += handler.handleCommand(line)
        }

        if buffer == reference { return "" }
        return """
        Swift output differs from KataGo reference for \(name).
        --- Swift (\(buffer.count) bytes) ---
        \(buffer)
        --- Reference (\(reference.count) bytes) ---
        \(reference)
        """
    }

    // MARK: - undo

    @Test func fixture_undo_empty() throws {
        let diff = try runFixture("undo_empty")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_undo_with_capture() throws {
        let diff = try runFixture("undo_with_capture")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_undo_after_pass() throws {
        let diff = try runFixture("undo_after_pass")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_undo_after_fixed_handicap() throws {
        let diff = try runFixture("undo_after_fixed_handicap")
        #expect(diff.isEmpty, "\(diff)")
    }

    // MARK: - fixed_handicap

    @Test func fixture_fixed_handicap_2_19() throws {
        let diff = try runFixture("fixed_handicap_2_19")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_fixed_handicap_9_19() throws {
        let diff = try runFixture("fixed_handicap_9_19")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_fixed_handicap_5_13() throws {
        let diff = try runFixture("fixed_handicap_5_13")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_fixed_handicap_err_too_small() throws {
        let diff = try runFixture("fixed_handicap_err_too_small")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_fixed_handicap_err_even_dim() throws {
        let diff = try runFixture("fixed_handicap_err_even_dim")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_fixed_handicap_err_not_empty() throws {
        let diff = try runFixture("fixed_handicap_err_not_empty")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_fixed_handicap_err_above_nine() throws {
        let diff = try runFixture("fixed_handicap_err_above_nine")
        #expect(diff.isEmpty, "\(diff)")
    }

    // MARK: - set_free_handicap

    @Test func fixture_set_free_handicap_basic() throws {
        let diff = try runFixture("set_free_handicap_basic")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_set_free_handicap_undo() throws {
        let diff = try runFixture("set_free_handicap_undo")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_set_free_handicap_err_pass() throws {
        let diff = try runFixture("set_free_handicap_err_pass")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_set_free_handicap_err_dup() throws {
        let diff = try runFixture("set_free_handicap_err_dup")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_set_free_handicap_err_nolibs() throws {
        let diff = try runFixture("set_free_handicap_err_nolibs")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_set_free_handicap_err_not_empty() throws {
        let diff = try runFixture("set_free_handicap_err_not_empty")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_set_free_handicap_empty_args() throws {
        let diff = try runFixture("set_free_handicap_empty_args")
        #expect(diff.isEmpty, "\(diff)")
    }

    @Test func fixture_set_free_handicap_clear_cycle() throws {
        let diff = try runFixture("set_free_handicap_clear_cycle")
        #expect(diff.isEmpty, "\(diff)")
    }
}
